import {
  Activity,
  AlertOctagon,
  AlertTriangle,
  ArrowLeftRight,
  Blocks,
  BookOpen,
  Boxes,
  Bug,
  CheckSquare,
  ClipboardList,
  Cloud,
  Code2,
  Database,
  Feather,
  FileCode2,
  FileText,
  Flame,
  FolderTree,
  Gauge,
  GitBranch,
  GraduationCap,
  Hammer,
  HardDrive,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  Network,
  Package,
  Palette,
  Plug,
  Rocket,
  Route,
  Search,
  Server,
  Settings2,
  Shield,
  ShieldAlert,
  ShoppingCart,
  Siren,
  SquareTerminal,
  Tags,
  Terminal,
  Timer,
  Waypoints,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Central icon registry. Everything in the UI references an icon by key,
 * so data files stay plain strings and the visual system stays consistent.
 */
export const ICONS: Record<string, LucideIcon> = {
  // sections
  errors: AlertOctagon,
  wordpress: Blocks,
  plugins: Plug,
  themes: Palette,
  woocommerce: ShoppingCart,
  elementor: LayoutTemplate,
  lms: GraduationCap,
  mysql: Database,
  hosting: Server,
  php: Code2,
  apache: Feather,
  nginx: Zap,
  performance: Gauge,
  security: Shield,
  migration: Package,
  deployment: Rocket,
  runbooks: Siren,
  checklists: ListChecks,
  "decision-trees": Waypoints,
  // nav / misc
  dashboard: LayoutDashboard,
  "knowledge-base": BookOpen,
  categories: FolderTree,
  "cheat-sheets": SquareTerminal,
  tools: Wrench,
  resources: FileText,
  tags: Tags,
  contribute: GitBranch,
  search: Search,
  // checklists
  "pre-launch": Rocket,
  "checklist-migration": Package,
  "checklist-security": Shield,
  "checklist-performance": Gauge,
  "checklist-woocommerce": ShoppingCart,
  debug: Bug,
  "incident-response": Siren,
  // runbooks
  "site-down": Siren,
  "payment-failure": ShoppingCart,
  "white-screen": AlertTriangle,
  "plugin-conflict": Plug,
  // decision trees
  "website-down": Activity,
  "broken-layout": Palette,
  "checkout-failing": ShoppingCart,
  "email-not-sending": Mail,
  // cheat sheets
  "wp-cli": Terminal,
  "cs-mysql": Database,
  permissions: Lock,
  ftp: HardDrive,
  "cs-php": Code2,
  "cs-apache": Feather,
  "cs-nginx": Network,
  cloudflare: Cloud,
  git: GitBranch,
  // callouts
  note: Info,
  tip: Lightbulb,
  warning: AlertTriangle,
  danger: ShieldAlert,
  investigate: Search,
  // workflow
  reproduce: ArrowLeftRight,
  evidence: ClipboardList,
  logging: FileCode2,
  isolate: Layers,
  variable: Settings2,
  fix: Hammer,
  verify: CheckSquare,
  // toolkit
  logs: FileText,
  boxes: Boxes,
  lifebuoy: LifeBuoy,
  timer: Timer,
  route: Route,
  flame: Flame,
  key: KeyRound,
};

export function Icon({
  name,
  className = "h-4 w-4",
  strokeWidth = 1.75,
  style,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
  style?: React.CSSProperties;
}) {
  const Cmp = ICONS[name] ?? FileText;
  return <Cmp className={className} strokeWidth={strokeWidth} style={style} aria-hidden />;
}
